### ISSUE TITLE
Question: why use fieldsets

### ISSUE THREAD

**Issue by xixiaofinland** [sfcure/CloneOpp#1]
Hi,

Thanks for this great share. It does one thing, and does it well :)!

One question:  
I see that when users define what fields to be cloned, the fieldsets are used. I understand that fieldSets are meant for grouping fields. Thus I am not sure why it is used and if other options available too?

Good work!

Br,
Xi

**Comment by sfcure** [comment]
I used the fieldset so users can decide which fields they want to copy in the cloned records. Now, in the latest package, I have removed the use of fieldsets.

**Comment by sfcure** [comment]
Since you question has been answered so closing it.
