### ISSUE TITLE
Issue with cancel button on Line Item modal

### ISSUE THREAD

**Issue by fischerjade** [sfcure/CloneOpp#3]
Just after I added this code to the org I tested it and found that when I click on the cancel button it throws an error:
  Uncaught Action failed: c:CloneOpportunity$controller$navigateToOppReview 
  [helper.navigateToRecord is not a function]

I fixed this by add the navigateToRecord method to the js controller and using that method instead of navigateToOppReview.  Don't know if this is ok I just wanted to let you know.

**Comment by sfcure** [comment]
This is fixed in the latest commit. I forgot to commit after fixing this issue.
