### ISSUE TITLE
Clone with a custom products object

### ISSUE THREAD

**Issue by JohanBendz** [sfcure/CloneOpp#5]
Hi Naval, great job with the add on!

I'm a bit new to Salesforce and just discovered some things are missing.. like this function.
Then I found your solution and tried it out and it works great, ...but... we have a custom object for handling quote lines, not using the standard product2 object.

Looking at the code I think I understand what's going on  but I would really appreciate if you could point out what needs to be changed to be able to use a custom object instead of the Products one.

**Comment by sfcure** [comment]
@JohanBendz 

You just need to change the OpportunityLineItem object references with your custom object and it should work. 

Just look for the **OpportunityLineItem** and it's **fields** references and you will get an idea where changes needs to be made.

**Comment by JohanBendz** [comment]
@sfcure Thanks! Made my day! :)
